"""SOP LLM - Constants.

Константы приложения.
"""

# API
API_PREFIX = "/api/v1"
API_VERSION = "1.0.0"

# Cache
CACHE_PREFIX = "sop_llm:"
CACHE_TTL_DEFAULT = 600  # секунд

# Pagination
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

# Tasks
TASK_STATUS_PENDING = "pending"
TASK_STATUS_PROCESSING = "processing"
TASK_STATUS_COMPLETED = "completed"
TASK_STATUS_FAILED = "failed"

# LLM
DEFAULT_TEMPERATURE = 0.7
DEFAULT_MAX_TOKENS = 4096
DEFAULT_TOP_P = 0.9

# Monitoring
WS_HEARTBEAT_INTERVAL = 30  # секунд
MAX_ERROR_HISTORY = 100

# HTTP Status Codes
HTTP_200_OK = 200
HTTP_201_CREATED = 201
HTTP_400_BAD_REQUEST = 400
HTTP_404_NOT_FOUND = 404
HTTP_422_VALIDATION_ERROR = 422
HTTP_500_INTERNAL_ERROR = 500
HTTP_503_SERVICE_UNAVAILABLE = 503

# Error Codes
ERROR_VALIDATION = "VALIDATION_ERROR"
ERROR_NOT_FOUND = "NOT_FOUND"
ERROR_INTERNAL = "INTERNAL_ERROR"
ERROR_SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
ERROR_MODEL_NOT_LOADED = "MODEL_NOT_LOADED"
ERROR_PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
ERROR_JSON_PARSE = "JSON_PARSE_ERROR"
ERROR_JSON_FIX_FAILED = "JSON_FIX_FAILED"
ERROR_MEMORY_EXCEEDED = "MEMORY_EXCEEDED"
