"""Константы для SOP LLM Executor.

Централизованное хранилище всех магических чисел и строк.
"""

DEFAULT_API_PREFIX = "/api/v1"
DEFAULT_DOCS_URL = "/docs"
DEFAULT_REDOC_URL = "/redoc"
DEFAULT_OPENAPI_URL = "/openapi.json"

DEFAULT_HTTP_TIMEOUT = 60
DEFAULT_WEBHOOK_TIMEOUT = 30
DEFAULT_JSON_FIXER_TIMEOUT = 30

DEFAULT_HTTP_MAX_RETRIES = 2
DEFAULT_WEBHOOK_MAX_RETRIES = 3
DEFAULT_LITELLM_MAX_RETRIES = 3

DEFAULT_SESSION_TTL = 3600
DEFAULT_IDEMPOTENCY_TTL = 86400

DEFAULT_LOGS_MAX_RECENT = 100

DEFAULT_CONTEXT_WINDOW = 4096
DEFAULT_MAX_TOKENS = 2048

DEFAULT_GPU_INDEX = 0
DEFAULT_MAX_VRAM_USAGE_PERCENT = 90.0
DEFAULT_VRAM_RESERVE_MB = 512

DEFAULT_EMBEDDING_MODEL = "intfloat/multilingual-e5-large"
DEFAULT_MODELS_DIR = "./models"

DEFAULT_REDIS_HOST = "redis"
DEFAULT_REDIS_PORT = 6379
DEFAULT_REDIS_DB = 1

DEFAULT_KAFKA_BOOTSTRAP_SERVERS = "kafka:9092"

DEFAULT_LANGFUSE_HOST = "http://langfuse:3000"

DEFAULT_CORS_ORIGINS = ["*"]

DEFAULT_SERVER_HOST = "0.0.0.0"
DEFAULT_SERVER_PORT = 8000

DEFAULT_APP_NAME = "SOP LLM Executor"

ISO_8601_FORMAT = "%Y-%m-%dT%H:%M:%S.%fZ"

REDIS_SESSION_PREFIX = "session:"
REDIS_IDEMPOTENCY_PREFIX = "idempotency:"
REDIS_QUEUE_KEY = "queue:tasks"
REDIS_PROCESSING_KEY = "queue:processing"
REDIS_LOGS_PREFIX = "logs:"
REDIS_LOGS_RECENT_KEY = "logs:recent"
REDIS_CONVERSATION_PREFIX = "conversation:"
REDIS_CONVERSATION_INDEX_KEY = "conversations:index"

DEFAULT_CONVERSATION_TTL = 86400 * 7
DEFAULT_MAX_CONVERSATION_MESSAGES = 100
DEFAULT_CONTEXT_MESSAGES_LIMIT = 50

DEFAULT_TOP_P = 1.0
DEFAULT_TOP_K = 40
DEFAULT_FREQUENCY_PENALTY = 0.0
DEFAULT_PRESENCE_PENALTY = 0.0
DEFAULT_PRIORITY = 0.0
DEFAULT_STREAM = False
DEFAULT_CLEANUP = True
